[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "glyn-manual"
authors = [{name = "Matchstick Studio", email = "support@matchstick.ug"}]
dynamic = ["version", "description"]
